/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  valerio
 * Created: 18-mag-2016
 */

/*Elimina tutte le Tabelle resettando cosi il Database Prima della nuova creazione*/
DROP TABLE  OggettoInVendita;
DROP TABLE  Utente;
DROP TABLE  CategoriaOggetti;

/* Crea Tabella Utente*/
CREATE TABLE Utente(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(128),
    tipoUtente VARCHAR(128),
    saldo REAL
)
;

/* Utenti Venditori*/
INSERT INTO Utente ( id, nome, cognome, username, password, tipoUtente ,saldo)
VALUES             ( default ,'Mario' , 'Rossi' , 'Venditore1' , 'Venditore1', 'Venditore', 0) ;

INSERT INTO Utente ( id, nome, cognome, username, password, tipoUtente ,saldo)
VALUES             ( default ,'Carlo' , 'Bianchi' , 'Venditore2' , 'Venditore2', 'Venditore', 0) ;

/* Utenti Clienti*/
INSERT INTO Utente ( id, nome, cognome, username, password, tipoUtente ,saldo)
VALUES             ( default ,'Paolo' , 'Verdi' , 'Cliente1' , 'Cliente1','Cliente', 100) ;

INSERT INTO Utente ( id, nome, cognome, username, password, tipoUtente ,saldo)
VALUES             ( default ,'Giovanni' , 'Gialli' , 'Cliente2' , 'Cliente2', 'Cliente', 50) ;


/* Crea Tabella CategoriaOggetti*/
CREATE TABLE CategoriaOggetti(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeCategoria VARCHAR(128),
    descrizione VARCHAR(32000)
)
;

/* Categoria di Oggetti*/
INSERT INTO CategoriaOggetti ( id, nomeCategoria, descrizione)
VALUES             ( default ,'oggettiBelli' , 'questi sono gli oggetti belli') ;

INSERT INTO CategoriaOggetti ( id, nomeCategoria, descrizione)
VALUES             ( default ,'oggettiBrutti' , 'questi sono gli oggetti brutti') ;

/* Crea Tabella OggettoInVendita*/
CREATE TABLE OggettoInVendita(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    urlImmagine VARCHAR(32000),
    quantita INTEGER,
    prezzo REAL,
    descrizione VARCHAR(32000),
    idVenditore INTEGER,
    idCategoria INTEGER
    
)
;

/* Inserimento degli oggetti nel database */

INSERT INTO OggettoInVendita ( id, nome, urlImmagine, quantita, prezzo, descrizione, idVenditore, idCategoria)
VALUES             ( default ,'Aria fresca' , 'src/img clienti/ariaFresca.jpg', 1000, 4.0, 'questa è aria Fresca', 1, 1 ) ;

INSERT INTO OggettoInVendita ( id, nome, urlImmagine, quantita, prezzo, descrizione, idVenditore, idCategoria)
VALUES             ( default ,'Sogni nel cassetto' , 'src/img clienti/SogniNelCassetto.jpg', 3, 40, 'bei sogni nel cassetto', 2, 1 ) ;

INSERT INTO OggettoInVendita ( id, nome, urlImmagine, quantita, prezzo, descrizione, idVenditore, idCategoria)
VALUES             ( default ,'Attico in centro' , 'src/img clienti/atticoInCentro.jpg', 1, 4000000.05, 'una dimora spartana', 2, 2 ) ;

INSERT INTO OggettoInVendita ( id, nome, urlImmagine, quantita, prezzo, descrizione, idVenditore, idCategoria)
VALUES             ( default ,'Tre Euri' , 'src/img clienti/tre_euro.jpg', 4, 2.99, 'monete sonanti', 1, 2 ) ;

INSERT INTO OggettoInVendita ( id, nome, urlImmagine, quantita, prezzo, descrizione, idVenditore, idCategoria)
VALUES             ( default ,'Un Abbraccio' , 'src/img clienti/unAbbraccio.png', 1000000000, 1.0, 'cado Abbraccio', 1, 1) ;
